# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlistdetail',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Bucketlist'),
        ),
    ]
